--创建G205表
create table G205(
	YEAR1 varchar,
	GCRQ text,
	GCZBS text,
	HOUR1 varchar,
	MINUTE1 varchar,
	CDH text,
	XSFX varchar,
	SBSBM varchar(20),
	DCSJLX varchar,
	SJXH varchar,
	CLZQ varchar,
	XKC varchar,
	DKC varchar,
	XHC varchar,
	ZHC varchar,
	DHC varchar,
	TDH varchar,
	JZX varchar,
	MTC varchar,
	TLJ varchar,
	XKCS varchar,
	DKCS varchar,
	XHCS varchar,
	ZHCS varchar,
	DHCS varchar,
	TDHS varchar,
	JZXS varchar,
	MTCS varchar,
	TLJS varchar,
	GCBFB varchar,
	PJCTJJ varchar,
	SJZYL varchar,
	FLAGS varchar,
	OFF_MINS varchar,
	ERR_CODE varchar,
	ERR_DESC varchar,
	DELETE_BY varchar,
	DELETE_TIME varchar,
	CREATE_BY varchar,
	CREATE_TIME text,
	UPDATE_BY varchar,
	UPDATE_TIME	text
);



--创建G205_678表
create table G205_678(
	YEAR1 varchar,
	GCRQ text,
	GCZBS text,
	HOUR1 varchar,
	XSFX varchar,
	DCSJLX varchar,
	TQ varchar,
	XKC varchar,
	DKC varchar,
	XHC varchar,
	ZHC varchar,
	DHC varchar,
	TDH varchar,
	JZX varchar,
	MTC varchar,
	TLJ varchar,
	RLC varchar,
	CLC varchar,
	ZXC varchar,
	KC varchar,
	HC varchar,
	QC varchar,
	JDC varchar,
	TOTAL varchar,
	KC_DL varchar,
	HC_DL varchar,
	QC_DL varchar,
	JDC_DL varchar,
	TOTAL_DL varchar,
	XKCS varchar,
	DKCS varchar,
	XHCS varchar,
	ZHCS varchar,
	DHCS varchar,
	TDHS varchar,
	JZXS varchar,
	MTCS varchar,
	TLJS varchar,
	KC_CS varchar,
	HC_CS varchar,
	QC_CS varchar,
	JDC_CS varchar,
	GCBFB varchar,
	PJCTJJ varchar,
	SJZYL varchar,
	FLAGS varchar,
	TIME_CNT varchar,
	DELETE_BY text,
	DELETE_TIME text,
	CREATE_BY text,
	CREATE_TIME text,
	UPDATE_BY text,
	UPDATE_TIME	text
);


--治超表创建
create table ZH_RS(
	en_station_name text,
	check_time text,
	vehicle_type varchar,
	weight varchar,
	alex_count,
	speed varchar,
	limit_weight varchar
);